---
title: "First Look at Data"
author: "Heidi Rodenhizer"
date: "`r Sys.Date()`"
output: html_document
---

# Load Libraries

```{r}
library(viridis)
library(readxl)
library(tidyverse)
```

```{r}
theme_set(theme_bw())
```


# Load Data

## Q1/3

```{r}
q1_3 = read_excel(
  './data/Q1_3.xlsx'#, 
  # range = 'A7:K402',
  # col_names = colnames(
  #   read_excel('./data/Q1_3.xlsx', n_max = 1)
  #   )
) |>
  filter(Respondent != 37) |>
  rename_with(~str_to_title(.)) |>
  rename_with(
    ~ str_split(.x, ' ', simplify = TRUE)[,3], 
    .cols = matches('level')
  ) |>
  mutate(
    Scenario = factor(
      case_when(
        Scenario == 'Present day' ~ 'Current',
        Scenario == 'A' ~ '1.5 C',
        Scenario == 'B' ~ '2 C',
        Scenario == 'C' ~ 'RCP 8.5'
      ),
      levels = c(
        'Current',
        '1.5 C',
        '2 C',
        'RCP 8.5'
      )
    ),
    Timescale = factor(
      case_when(Timescale == '2020' ~ 'Current',
                TRUE ~ as.character(Timescale)),
      levels = c('Current',
                 '2100',
                 '2300')
      )#,
    # Upper = case_when(Upper > 2000 ~ NA,
    #                   TRUE ~ Upper),
    # `Even Chance` = case_when(`Even Chance` > 2000 ~ NA,
    #                   TRUE ~ `Even Chance`),
    # Lower = case_when(Lower > 2000 ~ NA,
    #                   TRUE ~ Lower)
  ) |>
  rowwise() |>
  # rearrange values that are out of order
  mutate(
    estimate = median(
      c(as.numeric(Lower), 
        as.numeric(`Even Chance`), 
        as.numeric(Upper))
      ),
    lower = min(
      c(as.numeric(Lower), 
        as.numeric(`Even Chance`), 
        as.numeric(Upper))
      ),
    upper = max(
      c(as.numeric(Lower), 
        as.numeric(`Even Chance`), 
        as.numeric(Upper))
      ),
    .after = `Even Chance`
    ) |>
  ungroup() |>
  mutate(
    estimate = case_when(
      is.na(Lower) | is.na(`Even Chance`) | is.na(Upper) ~ as.numeric(`Even Chance`),
      TRUE ~ estimate
        ),
    lower = case_when(
      is.na(Lower) | is.na(`Even Chance`) | is.na(Upper) ~ as.numeric(Lower),
      TRUE ~ lower
        ),
    upper = case_when(
      is.na(Lower) | is.na(`Even Chance`) | is.na(Upper) ~ as.numeric(Upper),
      TRUE ~ upper
        )
    )

#   filter(
#     !(Respondent == 12 & Category == 'Biotic' & Question == 1) | # values given as percentages
#       !(Respondent == 18 & Category == 'Permafrost' & Question == 1) # lower and upper seemed mixed up, units may not have been Tg, and additional comments said numbers were limited to peatland C stocks
#     )
# 
# 
# # one respondent had unreasonably high values for question 1 - may have been total release rather than change between historical and present day?
# unreasonable_values = q1_3 |>
#   filter(Respondent == 2 & Category == 'Anthropogenic' & Question == '1.0') |>
#   mutate(Upper = NA, 
#          Lower = NA, 
#          `Even Chance` = NA)
```

```{r}
all_notes = q1_3 |>
  filter(!is.na(Flags)) |>
  pull(Flags)
all_notes

filter_out = all_notes[str_detect(all_notes, 'O|only') | str_detect(all_notes, 'percentage')]
filter_out
```

```{r}
# Percent of respondents with missing values or error
q1_3 |>
  summarise(errors = case_when(any(!is.na(Flags)) ~ 1,
                               TRUE ~ 0),
            .by = c(Respondent, Category)) |>
  summarise(error_rate = sum(errors)/n())

# Percent of rows with missing values or error
q1_3 |>
  mutate(errors = case_when(!is.na(Flags) ~ 1,
                            TRUE ~ 0)) |>
  summarise(error_rate = sum(errors)/n())


```

Long Version

```{r}
q1_3_long = q1_3 |>
  pivot_longer(Lower:`Even Chance`, 
               names_to = 'Estimate Type', 
               values_to = 'Carbon Impact') |>
  mutate(
    `Estimate Type` = factor(
      `Estimate Type`,
      levels = c(
        'Lower',
        'Even Chance',
        'Upper'
      )
    )
  )
```

Summarized Version

```{r}
q1_3_summary = q1_3 |>
  summarise(
    across(
      .cols = c(
        Upper, Lower, `Even Chance`, Expertise, Confidence
      ),
      ~ mean(.x, na.rm = TRUE),
      .names = '{.col} Mean'
    ),
    across(
      .cols = c(
        Upper, Lower, `Even Chance`, Expertise, Confidence
      ),
      ~ median(.x, na.rm = TRUE),
      .names = '{.col} Median'
    ),
    across(
      .cols = c(
        Upper, Lower, `Even Chance`, Expertise, Confidence
      ),
      ~ sd(.x, na.rm = TRUE),
      .names = '{.col} SD'
    ),
    across(
      .cols = c(
        Upper, Lower, `Even Chance`, Expertise, Confidence
      ),
      ~ sd(.x, na.rm = TRUE)/n(),
      .names = '{.col} SE'
    ),
    .by = c(Question, `Whole Question`, Category, Scenario, Timescale)
  ) |>
  mutate(
    `Dodged Timescale` = case_when(
      Scenario %in%  c('Current', '2 C') ~ as.numeric(Timescale),
      Scenario == '1.5 C' ~ as.numeric(Timescale) - 0.3,
      Scenario == 'RCP 8.5' ~ as.numeric(Timescale) + 0.3
    )
  )
```


## Q2

```{r}
q2 = read_excel('./data/Q2.xlsx', 
  range = 'A7:L363',
  col_names = colnames(
    read_excel('./data/Q2.xlsx', range = 'A1:L1')
    )
) |>
  rename_with(~str_to_title(.)) |>
  rename_with(
    ~ str_split(.x, ' ', simplify = TRUE)[,3], 
    .cols = matches('level')
  ) |>
  mutate(
    across(
      .cols = c(Frequency, Extent, Range, Severity),
      ~ case_when(.x == '-' ~ '0',
                  TRUE ~ .x) |>
        as.numeric()
    ),
    across(
      .cols = c(Expertise, Confidence),
      ~ as.numeric(.x)
      ),
    Scenario = factor(
      case_when(
        Scenario == 'A' ~ '1.5 C',
        Scenario == 'B' ~ '2 C',
        Scenario == 'C' ~ 'RCP 8.5',
        Scenario == 'c' ~ 'RCP 8.5'
      ),
      levels = c(
        '1.5 C',
        '2 C',
        'RCP 8.5'
      )
    ),
    Timescale = factor(
      case_when(Timescale == '2020' ~ 'Current',
                TRUE ~ as.character(Timescale)),
      levels = c('Current',
                 '2100',
                 '2300')
      )
  ) |>
  mutate(`Whole Question` = as.numeric(str_sub(Question, 1, 1)),
         .after = Respondent)
```

Long Version
```{r}
q2_long = q2 |>
  pivot_longer(Frequency:Severity, 
               names_to = 'Variable', 
               values_to = 'Disturbance Change')
```

Summarized Version

```{r}
q2_summary = q2 |>
  mutate(`Whole Question` = as.numeric(str_sub(Question, 1, 1))) |>
  summarise(
    across(
      .cols = c(
        Frequency, Extent, Range, Severity, Expertise, Confidence
      ),
      ~ mean(.x, na.rm = TRUE),
      .names = '{.col} Mean'
    ),
    across(
      .cols = c(
        Frequency, Extent, Range, Severity, Expertise, Confidence
      ),
      ~ median(.x, na.rm = TRUE),
      .names = '{.col} Median'
    ),
    across(
      .cols = c(
        Frequency, Extent, Range, Severity, Expertise, Confidence
      ),
      ~ sd(.x, na.rm = TRUE),
      .names = '{.col} SD'
    ),
    across(
      .cols = c(
        Frequency, Extent, Range, Severity, Expertise, Confidence
      ),
      ~ sd(.x, na.rm = TRUE)/n(),
      .names = '{.col} SE'
    ),
    .by = c(Question, `Whole Question`, Category, Scenario, Timescale)
  ) |>
  mutate(
    `Dodged Timescale` = case_when(
      Scenario %in%  c('Current', '2 C') ~ as.numeric(Timescale),
      Scenario == '1.5 C' ~ as.numeric(Timescale) - 0.3,
      Scenario == 'RCP 8.5' ~ as.numeric(Timescale) + 0.3
    )
  )
```


## Q4

```{r}
q4 = read_excel('./data/Q4_figure.xlsx', 
  range = 'A7:G317',
  col_names = colnames(
    read_excel('./data/Q4_figure.xlsx', range = 'A1:G1')
    )
) |>
  rename(Subquestion = `Sub-question (i-iv)`)  |>
  mutate(
    Aspect = case_when(
      Subquestion == 'i' ~ 'Spatial Variability',
      Subquestion == 'ii' ~ 'Temporal Variability',
      Subquestion == 'iii' ~ 'Direct Effects',
      Subquestion == 'iv' ~ 'Indirect Effects'
    ),
    across(.cols = c(Availability, Consensus),
           ~ (.x - 0.5)*2)
  )
```

## Completion Rates

```{r}
frame = expand_grid(Category = c('Anthropogenic',
                                 'Biotic',
                                 'Fire',
                                 'Permafrost',
                                 'Weather'),
                    `Whole Question` = c(1, 4),
                     Timescale = 'Current',
                     Completion = c('Missing', 'Partial', 'Complete')) |>
  rbind(
    expand_grid(Category = c('Anthropogenic',
                                 'Biotic',
                                 'Fire',
                                 'Permafrost',
                                 'Weather'),
                    `Whole Question` = c(2, 3),
                     Timescale = c('2100', '2300'),
                Completion = c('Missing', 'Partial', 'Complete'))
  ) |>
  mutate(
    Timescale = factor(
      Timescale,
      levels = c('Current', '2100', '2300')
    ),
    Completion = factor(
      Completion,
      levels = c('Missing', 'Partial', 'Complete')
    )
  )


respondents = q1_3 |>
  mutate(`Whole Question` = as.numeric(str_sub(Question, 1, 1))) |>
  summarise(
    Completion = factor(
      case_when(
        all(!is.na(Lower)) & all(!is.na(Upper)) & all(!is.na(`Even Chance`)) ~ 'Complete',
        any(!is.na(Lower)) | any(!is.na(Upper)) | any(!is.na(`Even Chance`)) ~ 'Partial',
        all(is.na(Lower)) & all(is.na(Upper)) & all(is.na(`Even Chance`)) ~ 'Missing'
      ),
      levels = c('Missing', 'Partial', 'Complete')
    ),
    .by = c(Respondent, Category, `Whole Question`, Timescale)
  ) |>
  rbind(
    q2_long |>
      mutate(`Whole Question` = as.numeric(str_sub(Question, 1, 1))) |>
      summarise(
        Completion = factor(
          case_when(
            all(!is.na(`Disturbance Change`)) ~ 'Complete',
            any(!is.na(`Disturbance Change`)) ~ 'Partial',
            all(is.na(`Disturbance Change`)) ~ 'Missing'
          ),
          levels = c('Missing', 'Partial', 'Complete')
        ),
        .by = c(Respondent, Category, `Whole Question`, Timescale)
      )
  ) |>
  rbind(
    q4 |>
      mutate(`Whole Question` = as.numeric(str_sub(Question, 1, 1))) |>
      summarise(
        Completion = factor(
          case_when(
            all(!is.na(Consensus)) & all(!is.na(Availability)) ~ 'Complete',
            any(!is.na(Consensus)) | any(!is.na(Availability)) ~ 'Partial',
            all(is.na(Consensus)) & all(is.na(Availability)) ~ 'Missing'
          ),
          levels = c('Missing', 'Partial', 'Complete')
        ),
        .by = c(Respondent, Category, `Whole Question`)
      ) |>
      mutate(Timescale = 'Current',
             .before = Completion)
  ) |>
  summarise(Count = n(),
            .by = c(Category, `Whole Question`, Timescale, Completion)) |>
  full_join(frame, by = c('Category', 'Whole Question', 'Timescale', 'Completion')) |>
  mutate(Count = case_when(is.na(Count) ~ 0,
                           TRUE ~ Count))
```


# Figures

```{r}
scenario_colors = c('gray30','#FFCC00', '#FF6600', '#990000')
```


## Number of Respondents

```{r, fig.height = 6.5, fig.width = 6.5}
ggplot(respondents,
       aes(x = Timescale, 
           y = Count, 
           color = Completion, 
           fill = Completion)) +
  geom_bar(width = 0.46, position = position_dodge(width = 0.5),
           stat = 'identity') +
  scale_color_viridis(discrete = TRUE,
                     direction = -1) +
  scale_fill_viridis(discrete = TRUE,
                     direction = -1) +
  scale_x_discrete(name = 'Question') +
  scale_y_continuous(name = 'Number of Respondents') +
  facet_grid(Category ~ `Whole Question`, scales = 'free_x') +
  theme(legend.position = 'bottom')

# ggsave('./figures/respondent_count.pdf',
#        height = 6.5, width = 6.5)
# ggsave('./figures/respondent_count.jpg',
#        height = 6.5, width = 6.5)
```


## Expertise

```{r}
expertise = rbind(
    q1_3 |>
      select(Respondent,
             Question,
             `Whole Question`, 
             Category, 
             Timescale, 
             Expertise),
    q2 |>
      select(Respondent,
             Question,
             `Whole Question`, 
             Category, 
             Timescale, 
             Expertise)
) |>
  distinct()

expertise_summary = expertise |>
  summarise(`Expertise Mean` = mean(Expertise, na.rm = TRUE),
            `Expertise Median` = median(Expertise, na.rm = TRUE),
            .by = c(Question, `Whole Question`, Category, Timescale))
```

```{r, fig.height = 6.5, fig.width = 6.5}
ggplot(expertise,
       aes(x = Expertise,
           fill = Timescale)
) +
  geom_bar(
    position = position_dodge(width = 0.75)
  ) +
  geom_vline(data = expertise_summary,
             aes(xintercept = `Expertise Mean`,
                 linetype = 'Mean')) +
  geom_vline(data = expertise_summary,
             aes(xintercept = `Expertise Median`,
                 linetype = 'Median')) +
  scale_fill_viridis(discrete = TRUE) +
  scale_linetype_manual(values = c('solid', 'dashed'),
                        guide = guide_legend(title = element_blank())) +
  scale_y_continuous(name = 'Number of Respondents',
                     breaks = seq(0, 12, by = 2)) +
  facet_grid(Category ~ Question, scales = 'free_x')

# ggsave('./figures/expertise.pdf',
#        height = 6.5,
#        width = 6.5)
# ggsave('./figures/expertise.jpg',
#        height = 6.5,
#        width = 6.5)
```


## Q1/Q3

### Violin Plot

```{r, fig.height = 6.5, fig.width = 6.5}
# Median values across respondents
ggplot(q1_3, 
       aes(x = Timescale,
           y = `Even Chance`,
           fill = Scenario)) +
  geom_hline(yintercept = 0,
             color = 'gray30') +
  geom_point(aes(y = `Even Chance`,
                 color = Scenario),
             position = position_jitterdodge(dodge.width = 0.9,
                                             jitter.width = 0.7,
                                             seed = 1),
             size = 1,
             alpha = 0.5) +
  geom_segment(aes(y = Lower,
                   yend = Upper,
                   color = Scenario),
             position = position_jitterdodge(dodge.width = 0.9,
                                             jitter.width = 0.7,
                                             seed = 1),
             width = 0,
             alpha = 0.5) +
  geom_violin(color = 'gray10',
              alpha = 0.25,
              position = position_dodge(width = 0.9)) +
  # scale_color_viridis(name = 'Emissions\nPathway',
  #                     begin = 0.1,
  #                     end = 0.9,
  #                     discrete = TRUE,
  #                     option = 'inferno',
  #                     direction = -1) +
  scale_color_manual(name = 'Emissions Pathway',
                     values = scenario_colors,
                     guide = guide_legend(ncol = 2)) +
  scale_fill_manual(name = 'Emissions Pathway',
                     values = scenario_colors,
                     guide = guide_legend(ncol = 2)) +
  geom_linerange(data = q1_3_summary,
                 aes(xmin = `Dodged Timescale` - 0.1, 
                     xmax = `Dodged Timescale` + 0.1,
                     y = `Even Chance Median`,
                     linewidth = 'Even Chance'),
                 color = 'black') +
  geom_linerange(data = q1_3_summary,
                 aes(xmin = `Dodged Timescale` - 0.075, 
                     xmax = `Dodged Timescale` + 0.075,
                     y = `Lower Median`,
                     linewidth = 'Lower/Upper'),
                 color = 'black') +
  geom_linerange(data = q1_3_summary,
                 aes(xmin = `Dodged Timescale` - 0.075, 
                     xmax = `Dodged Timescale` + 0.075,
                     y = `Upper Median`,
                     linewidth = 'Lower/Upper'),
                 color = 'black') +
  scale_linewidth_manual(
    name = 'Median Values',
    values = c(0.7, 0.3),
    # guide = guide_legend(
    #   theme = theme(legend.title = element_blank())
    # )
  ) +
  scale_y_continuous(name = expression('Tg C yr'^-1),
                     transform = "asinh",
                     breaks = c(-1000, -100, -10, -1, 0, 1, 10, 100, 1000, 10000),
                     minor_breaks = c(
                       seq(-4000, -1000, by = 1000),
                       seq(-900, -100, by = 100),
                       seq(-90, -10, by = 10),
                       seq(-9, -1, by = 1),
                       seq(-0.9, -0.1, by = 0.1),
                       seq(0.1, 0.9, by = 0.1),
                       seq(1, 9, by = 1),
                       seq(10, 90, by = 10),
                       seq(100, 900, by = 100),
                       seq(1000, 9000, by = 1000),
                       seq(10000, 50000, by = 10000)
                     ),
                     # labels = function(x) format(x, scientific = TRUE),
                     # minor_breaks = c(
                     #   -500, -50, -5, -0.5, 0.5, 5, 50, 500, 5000
                     #   ),
                     guide = "axis_logticks") +
  facet_wrap(~ Category, ncol = 2) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = 'inside',
        legend.position.inside = c(0.75, 0.13),
        legend.justification = c(0.5, 0.5))

# ggsave('./figures/q1_3_violin.pdf',
#        height = 6.5, width = 6.5)
# ggsave('./figures/q1_3_violin.jpg',
#        height = 6.5, width = 6.5)
```


### Histograms

```{r}
# lower
ggplot(q1_3, 
       aes(x = Lower,
           color = Scenario)) +
  geom_density() +
  scale_color_manual(name = 'Emissions\nPathway',
                     values = scenario_colors) +
  facet_grid(Question ~ Category, scales = 'free') +
  ggtitle('Lower')

# upper
ggplot(q1_3, 
       aes(x = Upper,
           color = Scenario)) +
  geom_density() +
  scale_color_manual(name = 'Emissions\nPathway',
                     values = scenario_colors) +
  facet_grid(Timescale ~ Category, scales = 'free') +
  ggtitle('Upper')

# even chance
ggplot(q1_3, 
       aes(x = `Even Chance`,
           color = Scenario)) +
  geom_density() +
  scale_color_manual(name = 'Emissions\nPathway',
                     values = scenario_colors) +
  facet_grid(Timescale ~ Category, scales = 'free') +
  ggtitle('Even Chance')
```

### Summarized Values
Even chance values which fall outside of lower-upper range, could be due to some people not filling in all boxes?

```{r}
# Mean values across respondents
ggplot(q1_3_summary, 
       aes(x = Timescale,
           color = Scenario)) +
  geom_hline(yintercept = 0,
             color = 'gray30') +
  geom_point(aes(y = `Lower Mean`),
             position = position_dodge(width = 0.75),
             size = 2,
             alpha = 0.5) +
  geom_errorbar(aes(ymin = `Lower Mean` - `Lower SD`,
                    ymax = `Lower Mean` + `Lower SD`),
             position = position_dodge(width = 0.75),
             width = 0.25,
             alpha = 0.5) +
  geom_point(aes(y = `Even Chance Mean`),
             position = position_dodge(width = 0.75),
             size = 3) +
  geom_errorbar(aes(ymin = `Even Chance Mean` - `Even Chance SD`,
                    ymax = `Even Chance Mean` + `Even Chance SD`),
             position = position_dodge(width = 0.75),
             width = 0.5) +
  geom_point(aes(y = `Upper Mean`),
             position = position_dodge(width = 0.75),
             size = 2,
             alpha = 0.5) +
  geom_errorbar(aes(ymin = `Upper Mean` - `Upper SD`,
                    ymax = `Upper Mean` + `Upper SD`),
             position = position_dodge(width = 0.75),
             width = 0.25,
             alpha = 0.5) +
  # scale_color_viridis(name = 'Emissions\nPathway',
  #                     begin = 0.1,
  #                     end = 0.9,
  #                     discrete = TRUE,
  #                     option = 'inferno',
  #                     direction = -1) +
  scale_y_continuous(name = expression('Tg C yr'^-1)) +
  scale_color_manual(name = 'Emissions\nPathway',
                     values = scenario_colors) +
  facet_grid(Category ~ ., scales = 'free_y') +
  theme(axis.title.x = element_blank()) +
  ggtitle('Mean Even Chance (bold), Lower, and Upper (lighter) Carbon Impact Across Respondents (Errorbars are Std Dev)')

# Median values across respondents
ggplot(q1_3_summary, 
       aes(x = Timescale,
           color = Scenario)) +
  geom_hline(yintercept = 0,
             color = 'gray30') +
  geom_point(aes(y = `Lower Median`),
             position = position_dodge(width = 0.75),
             size = 2,
             alpha = 0.5) +
  geom_errorbar(aes(ymin = `Lower Median` - `Lower SD`,
                    ymax = `Lower Median` + `Lower SD`),
             position = position_dodge(width = 0.75),
             width = 0.25,
             alpha = 0.5) +
  geom_point(aes(y = `Even Chance Median`),
             position = position_dodge(width = 0.75),
             size = 3) +
  geom_errorbar(aes(ymin = `Even Chance Median` - `Even Chance SD`,
                    ymax = `Even Chance Median` + `Even Chance SD`),
             position = position_dodge(width = 0.75),
             width = 0.5) +
  geom_point(aes(y = `Upper Median`),
             position = position_dodge(width = 0.75),
             size = 2,
             alpha = 0.5) +
  geom_errorbar(aes(ymin = `Upper Median` - `Upper SD`,
                    ymax = `Upper Median` + `Upper SD`),
             position = position_dodge(width = 0.75),
             width = 0.25,
             alpha = 0.5) +
  # scale_color_viridis(name = 'Emissions\nPathway',
  #                     begin = 0.1,
  #                     end = 0.9,
  #                     discrete = TRUE,
  #                     option = 'inferno',
  #                     direction = -1) +
  scale_y_continuous(name = expression('Tg C yr'^-1)) +
  scale_color_manual(name = 'Emissions\nPathway',
                     values = scenario_colors) +
  facet_grid(Category ~ ., scales = 'free_y') +
  theme(axis.title.x = element_blank()) +
  ggtitle('Median Even Chance (bold), Lower, and Upper (lighter) Carbon Impact Across Respondents (Errorbars are Std Dev)')
```

```{r, fig.height = 6.5, fig.width = 6.5}
# all 3 in one plot, but with boxplots
ggplot(q1_3_long, 
       aes(x = Timescale,
           fill = Scenario)) +
  geom_hline(yintercept = 0,
             color = 'gray30') +
  geom_boxplot(aes(y = `Carbon Impact`),
               color = 'black',
               linewidth = 0.25,
               outlier.size = 0.5) +
  # scale_color_viridis(name = 'Emissions\nPathway',
  #                     begin = 0.1,
  #                     end = 0.9,
  #                     discrete = TRUE,
  #                     option = 'inferno',
  #                     direction = -1) +
  scale_y_continuous(name = expression('Tg C yr'^-1)) +
  scale_fill_manual(name = 'Emissions\nPathway',
                     values = scenario_colors) +
  facet_grid(Category ~ `Estimate Type`, scales = 'free_y') +
  theme(axis.title.x = element_blank())

# ggsave('./figures/q1_3_overview.pdf',
#        height = 6.5,
#        width = 6.5)
# ggsave('./figures/q1_3_overview.jpg',
#        height = 6.5,
#        width = 6.5)
```

### Q1 Confidence

```{r, fig.height = 6.5, fig.width = 4}
ggplot(q1_3 |>
         filter(Question == '1.0')
) +
  geom_bar(aes(x = Confidence),
           position = position_dodge()) +
  geom_vline(data = q1_3_summary |>
               filter(Question == '1.0'),
             aes(xintercept = `Confidence Mean`,
                 linetype = 'Mean')) +
  geom_vline(data = q1_3_summary |>
               filter(Question == '1.0'),
             aes(xintercept = `Confidence Median`,
                 linetype = 'Median')) +
  scale_linetype_manual(
    values = c('solid', 'dashed'),
    guide = guide_legend(title = element_blank())
  ) +
  scale_y_continuous(name = 'Number of Respondents',
                     breaks = seq(0, 10, by = 2)) +
  facet_grid(Category ~ .)

# ggsave('./figures/q1_confidence.pdf',
#        height = 6.5, 
#        width = 4)
# ggsave('./figures/q1_confidence.jpg',
#        height = 6.5, 
#        width = 4)
```

### Q3 Confidence

```{r, fig.height = 6.5, fig.width = 6.5}
ggplot(
  q1_3 |>
         filter(Question == '3a')
) +
  geom_bar(aes(x = Confidence),
           position = position_dodge()) +
  geom_vline(data = q1_3_summary |>
               filter(Question == '3a'),
             aes(xintercept = `Confidence Mean`,
                 linetype = 'Mean')) +
  geom_vline(data = q1_3_summary |>
               filter(Question == '3a'),
             aes(xintercept = `Confidence Median`,
                 linetype = 'Median')) +
  scale_linetype_manual(
    values = c('solid', 'dashed'),
    guide = guide_legend(title = element_blank())
  ) +
  scale_y_continuous(name = 'Number of Respondents',
                     breaks = seq(0, 10, by = 2)) +
  facet_grid(Category ~ Scenario)

# ggsave('./figures/q3a_confidence.pdf',
#        height = 6.5, 
#        width = 6.5)
# ggsave('./figures/q3a_confidence.jpg',
#        height = 6.5, 
#        width = 6.5)
```

```{r, fig.height = 6.5, fig.width = 6.5}
ggplot(
  q1_3 |>
         filter(Question == '3b')
) +
  geom_bar(aes(x = Confidence),
           position = position_dodge()) +
  geom_vline(data = q1_3_summary |>
               filter(Question == '3b'),
             aes(xintercept = `Confidence Mean`,
                 linetype = 'Mean')) +
  geom_vline(data = q1_3_summary |>
               filter(Question == '3b'),
             aes(xintercept = `Confidence Median`,
                 linetype = 'Median')) +
  scale_linetype_manual(
    values = c('solid', 'dashed'),
    guide = guide_legend(title = element_blank())
  ) +
  scale_y_continuous(name = 'Number of Respondents',
                     breaks = seq(0, 10, by = 2)) +
  facet_grid(Category ~ Scenario)

# ggsave('./figures/q3b_confidence.pdf',
#        height = 6.5, 
#        width = 6.5)
# ggsave('./figures/q3b_confidence.jpg',
#        height = 6.5, 
#        width = 6.5)
```


## Q2

### Box Plot

```{r, fig.height = 6.5, fig.width = 6.5}
ggplot(q2_long, 
       aes(x = Timescale, 
           y = `Disturbance Change`, 
           fill = Scenario)) +
  geom_hline(yintercept = 0,
             color = 'gray30') +
  geom_boxplot(position = position_dodge(width = 0.75),
               color = 'black',
               linewidth = 0.25,
               outlier.size = 0.5) +
  scale_fill_manual(name = 'Emissions\nPathway',
                     values = scenario_colors[-1]) +
  scale_y_continuous(name = 'Change in Disturbance (%)',
                     breaks = seq(-3, 3),
                     labels = c('<= -50',
                                '-20 - -50',
                                '-5 - -20',
                                '-5 - 5',
                                '5 - 20',
                                '20 - 50',
                                '>= 50')) +
  facet_grid(Category ~ Variable)
  
# ggsave('./figures/q2_overview.pdf',
#        height = 6.5,
#        width = 6.5)
# ggsave('./figures/q2_overview.jpg',
#        height = 6.5,
#        width = 6.5)
```

## Q4

```{r, fig.height = 9, fig.width = 6.5}
ggplot(q4, aes(x = Availability, y = Consensus, color = Aspect)) +
  geom_hline(yintercept = 0,
             color = 'gray30') +
  geom_vline(xintercept = 0,
             color = 'gray30') +
  geom_point() +
  geom_text(data = tibble(
    x = c(-0.5, 0.5, -0.5, 0.5),
    y = c(0.95, 0.95, -0.95, -0.95),
    label = c('Established but\nIncomplete', 
              'Well Established', 
              'Speculative', 
              'Competing Explanations'),
    vjust = c(1, 1, 0, 0)
    ),
    aes(x = x, y = y, label = label, vjust = vjust),
    size = 2.5,
    inherit.aes = FALSE
            ) +
  scale_x_continuous(limits = c(-1, 1),
                     breaks = c(-1, 1),
                     labels = c('Low', 'High')) +
  scale_y_continuous(limits = c(-1, 1),
                     breaks = c(-1, 1),
                     labels = c('Low', 'High')) +
  scale_color_viridis(discrete = TRUE) +
  facet_wrap(~ Category, ncol = 2) +
  coord_fixed(expand = FALSE) +
  theme(legend.position = 'inside',
        legend.position.inside = c(0.75, 0.09),
        legend.justification = c(0.5, 0),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

# ggsave('./figures/q4_compiled.pdf',
#        height = 9,
#        width = 6.5)
# ggsave('./figures/q4_compiled.jpg',
#        height = 9,
#        width = 6.5)
```
